name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          
          config_display: large
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_achievements: true
          plugin_achievements_secrets: true
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X
          plugin_anilist: true
          plugin_anilist_user: Azrotho
          plugin_anilist_medias: anime
          plugin_anilist_limit: 32
          plugin_anilist_sections: favorites, watching
          plugin_wakatime: true
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
          plugin_wakatime_sections: time, editor, os
          config_order: base.header, wakatime, isocalendar, languages, achevements, anilist
          config_timezone: Europe/Paris
