name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 6,12,18 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_display: large
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_anilist: true
          plugin_anilist_user: Azrotho
          plugin_anilist_medias: anime
          plugin_anilist_limit: 32
          plugin_anilist_sections: favorites, watching
          plugin_wakatime: true
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graph, os
          plugin_fortune: true
          config_order: base.header, wakatime, base.activity+community, base.repositories,  isocalendar, languages, anilist, fortune
          config_timezone: Europe/Paris
